[omoi]
database-dir = "omoi-db"

[dhcp4]
domain-name = "kuaga.local"

[[dhcp4.subnet]]
subnet = "192.168.1.0"
netmask = "255.255.255.0"
range = ["192.168.1.201", "192.168.1.240"]
domain-name-servers = ["192.168.1.15"]
routers = ["192.168.1.1"]
broadcast-address = "192.168.1.255"
max-lease-time = 172800

[[dhcp4.host]]
name = "aoi"
hardware-ethernet = "dc:a6:32:e6:0f:44"
fixed-address = "192.168.1.15"
