[common]
database-dir = "omoi-db"

[debug]
hw-prefix = [0, 0, 0]

[dhcp4]
domain-name = "example.local"

[[dhcp4.subnet]]
subnet = "192.168.0.1"
netmask = "255.255.255.0"
range = ["192.168.0.101", "192.168.0.250"]
domain-name-servers = ["192.168.0.1"]
routers = ["192.168.0.1"]
broadcast-address = "192.168.0.255"
address-lease-time = 172800

[[dhcp4.host]]
name = "host1"
hardware-ethernet = "00:00:00:11:11:11"
fixed-address = "192.168.0.11"
